/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tasksApp;

//import java.util.List;
import controller.ProjectController;
//import model.Project;


public class App {

    public static void main(String[] args) {
        
        ProjectController projectController = new ProjectController();
      
        
        //Project project = new Project();
        //project.setName("testando2");
        //project.setDescription("meus gastos2");
        
        //projectController.save(project);
        
        //projectController.update(project);
        
        //projectController.removeById(2);
        
        //List<Project> projects = projectController.getAll();
        //System.out.println("total de projetos = " + projects.size());
        
        
        //project.setName("Novo nome do projeto");
        //projectController.update(project);
       
        //List<Project> projects = projectController.getAll();
        //System.out.println("Total de projetos =" + projects.size());
        
        
    }
    
     
}